### ISSUE TITLE
v0.3.13 error win32 x64

### ISSUE THREAD

**Issue by Ajit309** [microsoft/vscode-java-installer#174]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.13
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files\Common Files\Oracle\Java\javapath
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\Java\jdk-16.0.1\bin
C:\Users\ajitt\AppData\Local\Microsoft\WindowsApps
C:\Users\ajitt\AppData\Local\Programs\Microsoft VS Code\bin
JDKs:
C:\Program Files\Java\jdk-16.0.1	env.PATH,WindowsRegistry,DefaultLocation
```
log:
```
[16:18:33] Configure Java Settings
[16:18:33] Error occurred
[16:18:33] Error: Can not add index to parent of type string

```

**Comment by Eskibear** [comment]
The installer failed to update `java.home` in your vscode user settings. It can be syntax error but we are not sure. It would be great if you can provide content of your settings.json file. It shoule be located in `C:\Users\ajitt\AppData\Roaming\Code\User\settings.json`.

Back to your issue, since you have a JDK 16(>11) installed, you can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) in vscode, and it should work out of box.
