### ISSUE TITLE
V0.3.14 Error win32 x64

### ISSUE THREAD

**Issue by Jovikl** [microsoft/vscode-java-installer#188]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.14
env:
```
JAVA_HOME: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
PATH:
C:\Program Files (x86)\Microsoft\Edge\Application
C:\Program Files (x86)\Microsoft Office\Root\Office16\
C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin
C:\Program Files\Python39\Scripts\
C:\Program Files\Python39\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\Microsoft VS Code\bin
C:\Program Files\apache-maven-3.8.1\bin
C:\Program Files\Git\cmd
C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\
C:\Users\User\AppData\Local\Programs\Python\Python39\
C:\Users\User\AppData\Local\Microsoft\WindowsApps
C:\Program Files (x86)\Microsoft Office\root\Client
JDKs:
C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot	env.JAVA_HOME,env.PATH,WindowsRegistry,WindowsRegistry,DefaultLocation
```
log:
```
[19:41:31] Configure Java Settings
[19:41:31] Error occurred
[19:41:31] Error: Can not add index to parent of type string

```

**Comment by Eskibear** [comment]
The installer failed to update `java.home` in your vscode user settings. It can be syntax error but we are not sure. It would be great if you can provide content of your settings.json file. It shoule be located in `C:\Users\User\AppData\Roaming\Code\User\settings.json`.

Back to your issue, since you have a JDK 11 installed, you can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) in vscode, and it should work out of box.
