### ISSUE TITLE
v0.3.14 error win32 x64

### ISSUE THREAD

**Issue by rajawatvp** [microsoft/vscode-java-installer#189]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.14
env:
```
JAVA_HOME: C:\Users\vipin pratap\Documents\java
PATH:
C:\Program Files\Common Files\Oracle\Java\javapath
"C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files\Java\jdk-16.0.1\bin
C:\Users\vipin pratap\Documents\java\bin
"
C:\Python39\Scripts\
C:\Python39\
C:\python3.9\Scripts\
C:\python3.9\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files (x86)\dotnet\
C:\Users\vipin pratap\AppData\Local\Android\Sdk\platform-tools
C:\Program Files\nodejs\
C:\ProgramData\chocolatey\bin
C:\Users\vipin pratap\AppData\Roaming\npm
C:\Users\vipin pratap\AppData\Local\Programs\Microsoft VS Code\bin
JDKs:
C:\Program Files\Java\jdk-16.0.1	env.PATH,WindowsRegistry,DefaultLocation
```
log:
```
[8:22:21 AM] Configure Java Settings
[8:22:23 AM] Error occurred
[8:22:23 AM] Error: Can not add index to parent of type string

```

**Comment by rajawatvp** [comment]
please solve this issue

**Comment by Eskibear** [comment]
The installer failed to update `java.home` in your vscode user settings. It can be syntax error but we are not sure. It would be great if you can provide content of your settings.json file. It shoule be located in `C:\Users\vipin prata\AppData\Roaming\Code\User\settings.json`.

Back to your issue, since you have a JDK 16(>11) installed, you can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) in vscode, and it should work out of box.
